use crate::file::FileIndex;

#[derive(Clone, Debug, PartialEq)]
pub enum TokenKind {
    LeftParen,
    RightParen,
    LeftBrace,
    RightBrace,
    LeftBracket,
    RightBracket,
    Plus,
    PlusEqual,
    PlusPlus,
    Minus,
    MinusEqual,
    MinusMinus,
    MinusGreater,
    Star,
    StarEqual,
    Slash,
    SlashEqual,
    Equal,
    EqualEqual,
    Bang,
    BangEqual,
    Lesser,
    LesserEqual,
    LesserLesser,
    LesserLesserEqual,
    Greater,
    GreaterEqual,
    GreaterGreater,
    GreaterGreaterEqual,
    Semicolon,
    Comma,
    Amp,
    AmpEqual,
    AmpAmp,
    Bar,
    BarEqual,
    BarBar,
    Hat,
    HatEqual,
    Dot,
    DotDotDot,
    Tilde,
    Percent,
    PercentEqual,
    Colon,
    QuestionMark,

    ConstLong(i64),
    ConstULong(u64),
    ConstInt(i32),
    ConstUInt(u32),
    ConstFloat(f32),
    ConstDouble(f64),
    Ident(String),
    Str(String),

    KeywordReturn,
    KeywordIf,
    KeywordElse,
    KeywordFor,
    KeywordWhile,
    KeywordDo,
    KeywordInt,
    KeywordChar,
    KeywordLong,
    KeywordShort,
    KeywordFloat,
    KeywordDouble,
    KeywordSizeof,
    KeywordStruct,
    KeywordUnion,
    KeywordVoid,
    KeywordTypedef,
    KeywordBool,
    KeywordEnum,
    KeywordStatic,
    KeywordGoto,
    KeywordBreak,
    KeywordContinue,
    KeywordSwitch,
    KeywordCase,
    KeywordDefault,
    KeywordExtern,
    KeywordAlignof,
    KeywordAlignas,
    KeywordSigned,
    KeywordUnsigned,
    KeywordConst,
    KeywordVolatile,
    KeywordAuto,
    KeywordRegister,
    KeywordRestrict,
    KeywordRestrict1,
    KeywordRestrict2,
    KeywordNoreturn,

    EndOfFile,
}

pub type TokenIndex = usize;

#[derive(Debug, Clone, PartialEq)]
pub struct Token {
    pub kind: TokenKind,
    pub loc: usize,
    pub len: usize,
    pub file_index: FileIndex,
    pub line_no: usize,
    pub line_delta: usize,
    pub at_bol: bool,
    pub has_space: bool,
    pub origin: TokenIndex,
}

impl Token {
    /// Create a new token.
    pub fn new(kind: TokenKind, start: usize, end: usize) -> Self {
        Token {
            kind,
            loc: start,
            len: end - start,
            file_index: 0,
            line_no: 0,
            line_delta: 0,
            at_bol: false,
            has_space: false,
            origin: 0,
        }
    }
}
